#!/bin/bash

get_env_vars_file_name() {
  echo /tmp/ide/environment-`date +%Y-%m-%d_%H-%M-%S`
}

# Creates a file of format ENV_VAR_NAME="env var value" made up of current
# environment variables.
# $1 is a file path to which we save to
save_environment_variables() {

  # get all the bash variables set
  host_env=$(set -o posix ; set )

  # decide which variables to preserve
  DOCKER_ENVS_ARRAY=()
  # split IDE_VARS_BLACKLIST with ',' as delimeter
  blacklisted_variables=$(echo $IDE_VARS_BLACKLIST | tr "," "\n")
  for env_var in $host_env ; do
      env_var_name=$(echo $env_var | awk '{ gsub(/=.*/, ""); print }')

      blacklisted="false"
      for blacklisted_var in $blacklisted_variables ; do
          if [[ "$blacklisted_var" == *"*" ]]; then
              # this blacklisted variable ends with asterix, e.g. BASH*
              # get its name without asterix, e.g. BASH
              no_asterix_name=$(echo $blacklisted_var | awk '{ gsub(/\*/, ""); print }')

              if [[ "$env_var_name" == "$no_asterix_name"* ]]; then
                  DOCKER_ENVS_ARRAY+=("IDE_${env_var}")
                  blacklisted="true"
                  break;
              fi
          elif [[ "$env_var_name" == "$blacklisted_var" ]]; then
              DOCKER_ENVS_ARRAY+=("IDE_${env_var}")
              blacklisted="true"
              break;
          fi
      done
      if [[ "$blacklisted" == "false" ]]; then
          # this variable was not blacklisted, no need to add prefix before its name
          DOCKER_ENVS_ARRAY+=($env_var)
      fi
  done

  log_debug "Writing environment variables to $1"
  for env_var in "${DOCKER_ENVS_ARRAY[@]}" ; do
      echo "$env_var" >> "$1"
  done
}
