---
provisioner:
  name: dummy

verifier:
  name: shell
  command: /usr/local/bin/bats /tmp/bats
  remote_exec: true

platforms:
  - name: ubuntu
    transport:
      name: docker_cli
    driver:
      name: docker_cli
    driver_config:
      # make it a long running container:
      command: /bin/sh
      build_context: true
      image: ubuntu:14.04.2
      dockerfile: DockerfileUbuntu
  - name: alpine
    transport:
      name: docker_cli
    driver:
      name: docker_cli
    driver_config:
      # make it a long running container:
      command: /bin/sh
      build_context: true
      image: alpine:3.5
      dockerfile: DockerfileAlpine

suites:
  - name: default
    driver_config:
      volume:
        - <%= File.dirname(__FILE__) %>/test/integration/dummy_work:/ide/work
        - <%= File.dirname(__FILE__) %>/test/integration/default/bats:/tmp/bats
        - <%= File.dirname(__FILE__) %>/test/integration/default/30-not-executable-file.sh:/etc/ide.d/scripts/30-not-executable-file.sh
  - name: ssh
    driver_config:
      volume:
        - <%= File.dirname(__FILE__) %>/test/integration/dummy_work:/ide/work
        - <%= File.dirname(__FILE__) %>/test/integration/ssh/bats:/tmp/bats
        - <%= File.dirname(__FILE__) %>/test/integration/ssh/30-copy-ssh-configs.sh:/etc/ide.d/scripts/30-copy-ssh-configs.sh
        - <%= File.dirname(__FILE__) %>/test/integration/ssh/dummy_identity:/ide/identity
